version: '3.7'

services:
  server:
    container_name: server_web
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
      - ./db.json:/db.json
    ports:
        - "8080:8080"
    depends_on:
        - zipkin
        - prometheus
        - grafana
    networks:
      - observability

  zipkin:
    container_name: server_zipkin
    image: openzipkin/zipkin:2.24
    ports:
        - "9411:9411"
    networks:
      - observability

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.40.4
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
        - "9090:9090"
    networks:
      - observability

  grafana:
    container_name: grafana
    image: grafana/grafana:9.3.0
    ports:
        - "3000:3000"
        - "9100:9100"
    environment:
        - GF_SECURITY_ADMIN_USER=admin
        - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - grafana_data:/var/lib/grafana
    networks:
      - observability
    depends_on:
      - prometheus

networks:
    observability:
        driver: bridge

volumes:
    prometheus_data:
    grafana_data: